#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'

require 'soap/wsdlDriver'
wsdl = 'http://api.evilcode.net/lib/wsdl/DomOrder.wsdl'
driver = SOAP::WSDLDriverFactory.new(wsdl).create_rpc_driver

puts driver.inspect
